name: topdeck_app_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  logger: ^2.5.0
  flutter_secure_storage: ^9.2.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  font_awesome_flutter: ^10.8.0
  pine: ^1.0.3
  provider: ^6.0.5
  retrofit: ^4.4.1
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  auto_route: ^9.2.2
  favicon: ^1.1.0
  cached_network_image: ^3.2.3
  json_annotation: ^4.9.0
  sqlite3_flutter_libs: ^0.5.27
  path_provider: ^2.1.5
  path: ^1.9.0
  shared_preferences: ^2.3.3
  intl: ^0.20.2
  supabase_flutter: ^2.3.4
  uuid: ^4.3.3
  google_sign_in: ^6.3.0
  toastification: ^3.0.2
  app_links: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  bloc_test: ^9.1.0
  retrofit_generator: ^9.1.5
  auto_route_generator: ^9.0.0
  http_mock_adapter: ^0.6.1
  data_fixture_dart: ^2.2.0
  mockito: ^5.3.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
